// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-products.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function sb() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search the La Petite Bouteille catalogue by name. Returns active products only, with price in FCFA, slug, and short description.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Search term matched against product name."),
    limit: z.number().int().min(1).max(25).default(10).describe("Maximum number of results (1-25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const { data, error } = await sb().from("public_products").select("id, name, slug, price, short_description, image_url, stock_quantity").eq("is_active", true).ilike("name", `%${query}%`).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    const rows = data ?? [];
    const text = rows.length ? rows.map(
      (p) => `- ${p.name} (${p.price} FCFA) \u2014 /produit/${p.slug}${p.short_description ? ` \u2014 ${p.short_description}` : ""}`
    ).join("\n") : `No products found for "${query}".`;
    return {
      content: [{ type: "text", text }],
      structuredContent: { count: rows.length, products: rows }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sb2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product details",
  description: "Fetch a single product's full details by slug (e.g. from a product URL /produit/<slug>).",
  inputSchema: {
    slug: z2.string().trim().min(1).describe("Product slug from the URL.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const { data, error } = await sb2().from("public_products").select(
      "id, name, slug, price, original_price, description, short_description, tasting_notes, food_pairing, grape_variety, origin_country, region, vintage_year, volume_ml, alcohol_percentage, serving_temperature, stock_quantity, image_url, average_rating, review_count"
    ).eq("slug", slug).eq("is_active", true).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: `Product "${slug}" not found.` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { product: data }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
function sb3() {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "List categories",
  description: "List all product categories available in the La Petite Bouteille catalogue.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const { data, error } = await sb3().from("categories").select("id, name, slug, description").order("name");
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    const rows = data ?? [];
    const text = rows.length ? rows.map((c) => `- ${c.name} (/${c.slug})${c.description ? ` \u2014 ${c.description}` : ""}`).join("\n") : "No categories found.";
    return {
      content: [{ type: "text", text }],
      structuredContent: { count: rows.length, categories: rows }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "la-petite-bouteille-mcp",
  title: "La Petite Bouteille MCP",
  version: "0.1.0",
  instructions: "Tools to browse the La Petite Bouteille premium wine & spirits catalogue (Cameroon). Use `search_products` to find bottles by name, `get_product` for full details from a slug, and `list_categories` to explore the catalogue structure. Prices are in FCFA.",
  tools: [search_products_default, get_product_default, list_categories_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
